language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script: 
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/behat

